BEGIN TRANSACTION 
	Use SistemaReservas 		
	print 'Criando Tabelas'

	IF NOT EXISTS (SELECT * FROM SYS.TABLES WHERE NAME ='TB_FILIAL')
	BEGIN
		CREATE TABLE TB_FILIAL(
			CODFILIAL INT IDENTITY(1,1) NOT NULL,
			DESCRICAO VARCHAR(50),
			LOCALIDADE VARCHAR(100)
			CONSTRAINT PK_FILIAL PRIMARY KEY(CODFILIAL)
		)
	END

	IF NOT EXISTS (SELECT * FROM SYS.TABLES WHERE NAME ='TB_SALA')  
	BEGIN
		CREATE TABLE TB_SALA(
			CODSALA INT IDENTITY(1,1) NOT NULL, 
			CODFILIAL INT,
			DESCRICAO VARCHAR(100)
			CONSTRAINT PK_SALA PRIMARY KEY(CODSALA),
			CONSTRAINT FK_TB_SALA_FILIAL FOREIGN KEY(CODFILIAL) REFERENCES TB_FILIAL	
		)
	END 

	IF NOT EXISTS (SELECT * FROM SYS.TABLES WHERE NAME ='TB_USUARIO')
	BEGIN
		CREATE TABLE TB_USUARIO(
			CODUSUARIO INT IDENTITY(1,1) NOT NULL,
			NOME VARCHAR(100),
			MATRICULA CHAR(8)
			CONSTRAINT PK_USUARIO PRIMARY KEY(CODUSUARIO)
		)
	END


	IF NOT EXISTS (SELECT * FROM SYS.TABLES WHERE NAME ='TB_ACOMPANHAMENTO_ITEM')
	BEGIN
		CREATE TABLE TB_ACOMPANHAMENTO_ITEM(
			CODACOMPANHAMENTOITEM INT IDENTITY(1,1) NOT NULL,
			ITEM VARCHAR(50),
			DESCRICAO VARCHAR(100)
			CONSTRAINT PK_ACOMPANHAMENTO_ITEM PRIMARY KEY(CODACOMPANHAMENTOITEM)
		)
	END


	IF NOT EXISTS (SELECT * FROM SYS.TABLES WHERE NAME ='TB_RESERVA')
	BEGIN
		CREATE TABLE TB_RESERVA(
			CODRESERVA INT IDENTITY(1,1) NOT NULL,
			CODSALA INT,
			CODUSUARIO INT,
			DATAINICIO DATETIME,
			DATAFIM DATETIME,
			DESCRICAO VARCHAR(1000)
			CONSTRAINT PK_RESERVA  PRIMARY KEY(CODRESERVA), 
			CONSTRAINT FK_RESERVA_SALA FOREIGN KEY(CODSALA) REFERENCES TB_SALA,
			CONSTRAINT FK_RESERVA_USUARIO FOREIGN KEY(CODUSUARIO) REFERENCES TB_USUARIO
		)
	END


	IF NOT EXISTS (SELECT * FROM SYS.TABLES WHERE NAME ='TB_ACOMPANHAMENTO_ITEM_RESERVA')
	BEGIN
		CREATE TABLE TB_ACOMPANHAMENTO_ITEM_RESERVA(
			CODACOMPANHAMENTORESERVA INT IDENTITY(1,1) NOT NULL,
			CODACOMPANHAMENTOITEM INT,
			CODRESERVA INT,
			QUANTIDADE INT
			CONSTRAINT PK_ACOMPANHAMENTOITEMRESERVA PRIMARY KEY(CODACOMPANHAMENTORESERVA),
			CONSTRAINT FK_ACOMPANHAMENTOITEMRESERVA_ACOMPANHAMENTOITEM FOREIGN KEY(CODACOMPANHAMENTOITEM) REFERENCES TB_ACOMPANHAMENTO_ITEM,
			CONSTRAINT FK_ACOMPANHAMENTOITEMRESERVA_RESERVA FOREIGN KEY(CODRESERVA) REFERENCES TB_RESERVA
		)	
	END

	IF NOT EXISTS (SELECT * FROM SYS.TABLES WHERE NAME ='TB_MENSAGEM')
	BEGIN
		CREATE TABLE TB_MENSAGEM(
			COD int,
			DESCRICAO varchar(2000)
		)
	END

	print 'Criação das tabelas finalizada!'

IF @@ERROR <> 0
	ROLLBACK
ELSE
	COMMIT



 